// UI screenshots via a scripted session. node tools/uishots.mjs outdir w h
import { chromium } from '/opt/node22/lib/node_modules/playwright/index.mjs';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
const root = path.dirname(path.dirname(fileURLToPath(import.meta.url)));
const [outDir, w = '1280', h = '720', mobile = '0'] = process.argv.slice(2);
fs.mkdirSync(outDir, { recursive: true });
const browser = await chromium.launch({ args: ['--use-angle=swiftshader', '--enable-unsafe-swiftshader', '--ignore-gpu-blocklist'] });
const ctx = await browser.newContext({ viewport: { width: +w, height: +h }, hasTouch: mobile === '1', isMobile: mobile === '1', deviceScaleFactor: mobile === '1' ? 2 : 1 });
const page = await ctx.newPage();
const logs = [];
page.on('console', (m) => { if (!/ERR_CERT|already non-indexed|parallel_shader/.test(m.text())) logs.push(`[${m.type()}] ${m.text()}`); });
page.on('pageerror', (e) => logs.push(`[pageerror] ${e.message}`));
await page.goto('file://' + path.join(root, 'dist/deng-guanque-lou.html') + '?still=1&q=light');
await page.waitForFunction(() => window.__ready === true, null, { timeout: 240000 });
const snap = async (name) => { await page.evaluate(() => window.__dbg.step(1 / 30)); await page.screenshot({ path: path.join(outDir, name + '.png') }); };
await snap('01_landing');
await page.click('#btn-enter');
await page.evaluate(() => { window.__dbg.jump(1, 8); });
await snap('02_tour_l1');
await page.evaluate(() => { window.__dbg.jump(5, 16); });
await snap('03_tour_vision');
await page.click('#btn-toc');
await snap('04_toc');
await page.click('#toc-close');
await page.click('#btn-more');
await snap('05_more');
await page.keyboard.press('Escape');
await page.click('#btn-speech');
await page.waitForTimeout(300);
await snap('06_speech_fallback');
await page.click('#btn-text');
await page.evaluate(() => { window.__dbg.jump(2, 10); });
await snap('07_origonly');
await page.evaluate(() => window.__dbg.app.enterFree());
await snap('08_free');
await page.evaluate(() => window.__dbg.app.startTour());
await page.evaluate(() => { window.__dbg.jump(6, 19.9, true); });
for (let i = 0; i < 8; i++) await page.evaluate(() => window.__dbg.step(1 / 10));
await snap('09_ending');
console.log(JSON.stringify(await page.evaluate(() => window.__dbg.state())));
console.log(logs.join('\n'));
await browser.close();
